spring:
  application:
    name: tanzu-java-web-app
  config:
    import: optional:configserver:http://configserver:80/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
hello:
  greeting: "Greetings from local 1 application.yml"