spring:
  application:
    name: tanzu-java-web-app
  config:
    import: optional:configserver:http://configserver.default.svc.cluster.local
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
hello:
  greeting: "Greetings from local application.yml"