spring:
  application:
    name: tanzu-java-web-app
  config:
    import: optional:configserver:http://configserver-default.cnr.axon.devops.cloud-native.biz/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
hello:
  greeting: "Greetings from local 1 application.yml"

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG